### ISSUE TITLE
Warnings on parameters in crystal 1.5.0

### ISSUE THREAD

**Issue by confact** [athena-framework/athena#191] opened 2022-08-12 17:41 UTC
Getting errors on parameters for overridden methods, like these:
```
In /home/confact/.asdf/installs/crystal/1.5.0/share/crystal/src/json/any.cr:138:11
 
 138 | def dig(index_or_key : String | Int, *subkeys) : JSON::Any
               ^-----------
 Warning: positional parameter 'index_or_key' corresponds to parameter 'key_or_index' of the overridden method Athena::Serializer::Any#dig(key_or_index : String | Int, *keys), which has a different name and may affect named argument passing
```
It would be nice to get rid of.

**Comment by Blacksmoke16** [comment] 2022-08-12 17:51
Duplicate of #190

Were also some breaking changes that need to be released, so not as simple as a quick patch release. In the meantime you can use a shards override to upgrade the serializer to the latest commit to get the fix. The breaking changes are unlikely to affect anyone, so should be fine in the meantime.

```yaml
# shard.override.yml
dependencies:
  athena-serializer:
    github: athena-framework/serializer
    commit: 3757b3e93be0b5be7313e6c7ea1ac972584bf271
```

**Closed by Blacksmoke16** 2022-08-12 17:51 UTC
Labels: kind:bug, component:serializer, state:duplicate

**Comment by Blacksmoke16** [comment] 2022-08-12 18:04
Duplicate of #190

**Comment by Blacksmoke16** [comment] 2022-09-05 01:36
@confact As a heads up I ended up deciding the breaking changes are unlikely to affect really anyone at all, so will be getting a patch release out for all the effected components tomorrow. Once those are out can just `shards update` and should be good to go.
